/* ===== ACTON PRODUCT ===== */
export const FETCH_PRODUCT='FETCH_PRODUCT';
export const ADD_PRODUCT='ADD_PRODUCT';
export const UPDATE_PRODUCT='UPDATE_PRODUCT';
export const DELETE_PRODUCT='DELETE_PRODUCT';
export const UPDATE_STATUS_PRODUCT='UPDATE_STATUS_PRODUCT';
export const OPPOSITE_PRODUCT='OPPOSITE_PRODUCT';
export const SEARCH_PRODUCT='SEARCH_PRODUCT';
export const GET_BY_PRODUCT='GET_BY_PRODUCT'; 
export const PAGE_PRODUCT='PAGE_PRODUCT'; 
export const PRICE_PRODUCT='PRICE_PRODUCT';
/* ===== ACTON CATEGORY ===== */
export const FETCH_CATEGORY='FETCH_CATEGORY';
export const ADD_CATEGORY='ADD_CATEGORY';
export const UPDATE_CATEGORY='UPDATE_CATEGORY';
export const DELETE_CATEGORY='DELETE_CATEGORY';
export const UPDATE_STATUS_CATEGORY='UPDATE_STATUS_CATEGORY';
export const OPPOSITE_CATEGORY='OPPOSITE_CATEGORY';
export const SEARCH_CATEGORY='SEARCH_CATEGORY';
export const GET_BY_CATEGORY='GET_BY_CATEGORY'; 
export const PAGE_CATEGORY='PAGE_THEGROUP';  
/* ===== ACTON SIZE ===== */
export const FETCH_SIZE='FETCH_SIZE';
export const PAGE_SIZE='PAGE_SIZE';
export const ADD_SIZE='ADD_SIZE';
export const DELETE_SIZE='DELETE_SIZE';
export const SEARCH_SIZE='SEARCH_SIZE';
export const OPPOSITE_SIZE='OPPOSITE_SIZE';
/* ===== ACTON USER ===== */
export const PAGE_USER='PAGE_USER';
export const FETCH_USER='FETCH_USER';
export const ADD_USER='ADD_USER';
export const UPDATE_USER='UPDATE_USER';
export const DELETE_USER='DELETE_USER';
export const UPDATE_STATUS_USER='UPDATE_STATUS_USER';
export const OPPOSITE_USER='OPPOSITE_USER';
export const SEARCH_USER='SEARCH_USER';
/* ===== ACTON TRADEMARK ===== */
export const FETCH_TRADEMARK='FETCH_TRADEMARK';
export const ADD_TRADEMARK='ADD_TRADEMARK';
export const UPDATE_TRADEMARK='UPDATE_TRADEMARK';
export const DELETE_TRADEMARK='DELETE_TRADEMARK';
export const UPDATE_STATUS_TRADEMARK='UPDATE_STATUS_TRADEMARK';
export const OPPOSITE_TRADEMARK='OPPOSITE_TRADEMARK';
export const SEARCH_TRADEMARK='SEARCH_TRADEMARK';
/* ===== ACTON CART ===== */
export const ADD_CART= 'ADD_CART';
export const DELETE_CART= 'DELETE_CART';
export const UPDATE_CART= 'UPDATE_CART';
export const UPDATE_CART_SIZE='UPDATE_CART_SIZE';
/* ===== ACTON ORDER ===== */
export const FETCH_ORDER= 'FETCH_ORDER';
export const OPPOSITE_ORDER= 'OPPOSITE_ORDER';